#!/bin/sh
mirror="http://ftp.debian.org/debian/"
security_mirror="http://ftp.debian.org/debian-security/"
lb config noauto \
    -a i386 \
    -b hdd \
    -d sid \
    --linux-flavours 686-pae \
    --mode debian \
    --debian-installer live \
    --debian-installer-gui true \
    --bootappend-live "\
    boot=live \
    config \
    persistence-encryption=luks \
    username=paranoid \
    hostname=freepto \
    persistence \
    live-config.locales=it_IT.UTF-8 live-config.timezone=Europe/Rome live-config.keyboard-layouts=it \
    " \
    --archive-areas "main contrib non-free" \
    --apt-recommends true \
    --mirror-bootstrap "${mirror}" \
    --mirror-binary "${mirror}" \
    --mirror-chroot-security "${security_mirror}" \
    --mirror-binary-security "${security_mirror}" \
"${@}"
